import type { PlannerInput } from "@/schemas/planner.schema";
import type { TravelPlan } from "@/features/ai/schemas/travel-plan.schema";

export const plannerInputFixture: PlannerInput = {
  destination: "Tokyo",
  days: 2,
  budget: 800,
  currency: "USD",
  travelStyle: "first-time",
  companion: "couple",
  interests: ["food", "culture"],
  foodPreference: "local-food",
  transportation: "public-transit",
  accommodation: "not-booked",
  pace: "balanced",
  travelGoal: "first-visit",
  specialRequirement: "",
  language: "english",
  accessibility: "none",
  visa: "not-sure",
  hasFlights: false,
  hasHotel: false,
  mustVisitPlaces: "Senso-ji",
  avoidPlaces: "",
};

export const travelPlanFixture: TravelPlan = {
  id: "trip_tokyo_2d",
  destination: "Tokyo",
  durationDays: 2,
  title: "Tokyo First Visit",
  summary: "A compact first-time Tokyo plan focused on food, culture, and easy public transit.",
  hotelRecommendation: {
    area: "Ueno or Asakusa",
    fitReason: "Good access to classic sights and public transit for a first visit.",
    pros: ["Convenient transit", "Good food access"],
    cons: ["Can be busy"],
    sourceStatus: "estimated",
    confidence: 0.72,
  },
  days: [
    {
      id: "day_1",
      dayIndex: 1,
      title: "Asakusa and Ueno",
      theme: "Classic culture and local food",
      areaFocus: ["Asakusa", "Ueno"],
      summary: "Start with landmark culture and keep route distance low.",
      activities: [
        {
          id: "activity_1_1",
          title: "Senso-ji",
          type: "attraction",
          timeSlot: "morning",
          startTime: "09:30",
          durationMinutes: 120,
          location: {
            name: "Senso-ji",
            address: null,
            area: "Asakusa",
            lat: null,
            lng: null,
            placeId: null,
            sourceStatus: "estimated",
          },
          budget: {
            currency: "USD",
            min: 0,
            max: 10,
            category: "ticket",
            confidence: 0.8,
          },
          restaurant: null,
          transportToNext: {
            fromActivityId: "activity_1_1",
            toActivityId: "activity_1_2",
            mode: "public-transit",
            estimatedDurationMinutes: 25,
            distanceRisk: "low",
            notes: "Use nearby rail connections.",
            sourceStatus: "estimated",
          },
          reason: "It is a classic first-time Tokyo anchor.",
          userValue: "Helps the traveler feel oriented quickly.",
          sourceStatus: "estimated",
          confidence: 0.82,
          warnings: [],
          alternatives: [],
        },
        {
          id: "activity_1_2",
          title: "Ameyoko food walk",
          type: "restaurant",
          timeSlot: "lunch",
          startTime: "12:30",
          durationMinutes: 90,
          location: {
            name: "Ameyoko",
            address: null,
            area: "Ueno",
            lat: null,
            lng: null,
            placeId: null,
            sourceStatus: "estimated",
          },
          budget: {
            currency: "USD",
            min: 15,
            max: 35,
            category: "food",
            confidence: 0.7,
          },
          restaurant: {
            name: "Ameyoko casual food stalls",
            cuisine: "Japanese street food",
            mealType: "lunch",
            budget: {
              currency: "USD",
              min: 15,
              max: 35,
              category: "food",
              confidence: 0.7,
            },
            dietaryFit: [],
            routeFitReason: "Fits naturally after Asakusa and before Ueno.",
            sourceStatus: "estimated",
            confidence: 0.7,
          },
          transportToNext: null,
          reason: "Food-focused stop with flexible timing.",
          userValue: "Lets the user sample local food without a reservation.",
          sourceStatus: "estimated",
          confidence: 0.76,
          warnings: [],
          alternatives: [],
        },
      ],
      dailyBudget: {
        currency: "USD",
        min: 40,
        max: 90,
        food: 45,
        transport: 15,
        tickets: 10,
        shoppingBuffer: 20,
        confidence: 0.72,
      },
      routeRisk: "low",
      paceRisk: "low",
      warnings: [],
    },
    {
      id: "day_2",
      dayIndex: 2,
      title: "Shibuya and Harajuku",
      theme: "Modern Tokyo",
      areaFocus: ["Shibuya", "Harajuku"],
      summary: "A focused day for city energy, cafes, and shopping windows.",
      activities: [
        {
          id: "activity_2_1",
          title: "Meiji Shrine",
          type: "attraction",
          timeSlot: "morning",
          startTime: "09:30",
          durationMinutes: 90,
          location: {
            name: "Meiji Shrine",
            address: null,
            area: "Harajuku",
            lat: null,
            lng: null,
            placeId: null,
            sourceStatus: "estimated",
          },
          budget: {
            currency: "USD",
            min: 0,
            max: 10,
            category: "ticket",
            confidence: 0.8,
          },
          restaurant: null,
          transportToNext: null,
          reason: "Balances modern neighborhoods with a calm cultural stop.",
          userValue: "Keeps the day varied without complex routing.",
          sourceStatus: "estimated",
          confidence: 0.8,
          warnings: [],
          alternatives: [],
        },
      ],
      dailyBudget: {
        currency: "USD",
        min: 50,
        max: 120,
        food: 55,
        transport: 15,
        tickets: 10,
        shoppingBuffer: 40,
        confidence: 0.72,
      },
      routeRisk: "low",
      paceRisk: "low",
      warnings: [],
    },
  ],
  totalBudget: {
    currency: "USD",
    min: 90,
    max: 210,
    confidence: 0.72,
  },
  metadata: {
    promptVersion: "planner-v1",
    model: "test-model",
    locale: "en",
    generatedAt: "2026-07-09T00:00:00.000Z",
    inputHash: "fixture",
    retries: 0,
  },
  explain: {
    summary: "The plan groups activities by nearby neighborhoods.",
    routeLogic: ["Keep each day within nearby areas."],
    budgetLogic: ["Reserve food and transport buffers."],
    personalization: ["Food and culture prioritized."],
    tradeoffs: ["Specific live opening hours require verification."],
    verificationNeeded: ["Opening hours", "Transit disruptions"],
  },
  warnings: [],
  confidence: 0.76,
};
